
export const TRACKS = [
    {name: 'Melbourne', flag: '/assets/flags/australia.png'},
    {name: 'Paul Ricard', flag: '/assets/flags/france.png'},
    {name: 'Shanghai', flag: '/assets/flags/china.png'},
    {name: 'Sakhir (Bahrain)', flag: '/assets/flags/bahrain.png'},
    {name: 'Catalunya', flag: '/assets/flags/spain.png'},
    {name: 'Monaco', flag: '/assets/flags/monaco.png'},
    {name: 'Montreal', flag: '/assets/flags/canada.png'},
    {name: 'Silverstone', flag: '/assets/flags/great-britain.png'},
    {name: 'Hockenheim', flag: '/assets/flags/germany.png'},
    {name: 'Hungaroring', flag: '/assets/flags/hungary.png'},
    {name: 'Spa', flag: '/assets/flags/belgium.png'},
    {name: 'Monza', flag: '/assets/flags/italy.png'},
    {name: 'Singapore', flag: '/assets/flags/signapore.png'},
    {name: 'Suzuka', flag: '/assets/flags/japan.png'},
    {name: 'Abu Dhabi', flag: '/assets/flags/emirates.png'},
    {name: 'Texas', flag: '/assets/flags/usa.png'},
    {name: 'Brazil', flag: '/assets/flags/brazil.png'},
    {name: 'Austria', flag: '/assets/flags/austria.png'},
    {name: 'Sochi', flag: '/assets/flags/russia.png'},
    {name: 'Mexico', flag: '/assets/flags/mexico.png'},
    {name: 'Baku (Azerbaijan)', flag: '/assets/flags/azerbaijan.png'},
    {name: 'Sakhir Short', flag: '/assets/flags/bahrain.png'},
    {name: 'Silverstone Short', flag: '/assets/flags/great-britain.png'},
    {name: 'Texas Short', flag: '/assets/flags/usa.png'},
    {name: 'Suzuka Short', flag: '/assets/flags/japan.png'},
    {name: 'Hanoi', flag: '/assets/flags/vietnam.png'},
    {name: 'Zandvoort', flag: '/assets/flags/netherlands.png'},
    {name: 'Imola', flag: '/assets/flags/italy.png'},
    {name: 'Portimao', flag: '/assets/flags/portugal.png'},
    {name: 'Jeddah', flag: '/assets/flags/saudi.png'},
  ];